DELETE FROM match_data.action_catalog
WHERE version = 1 AND code IN (
  'SHOT_OFF_TARGET', 'SHOT_OFF_POST', 'CHANCE_CREATED', 'AERIAL_WON',
  'AERIAL_LOST', 'DRIBBLE_WON', 'CROSS', 'LOST_BALL', 'KEY_PASS', 'RECOVERY',
  'BLOCK', 'DUEL_WON', 'DUEL_LOST', 'DRIBBLED_PAST', 'CLEARANCE',
  'HEADER_CLEARED', 'GOALKEEPER_DIVING_SAVE', 'GOALKEEPER_CLAIM',
  'GOALKEEPER_PUNCH', 'GOALKEEPER_SWEEP', 'GOAL_CONCEDED',
  'DISTRIBUTION_LONG', 'DISTRIBUTION_SHORT'
);