DROP SCHEMA IF EXISTS read_model CASCADE;
DROP SCHEMA IF EXISTS platform CASCADE;
DROP SCHEMA IF EXISTS match_data CASCADE;
DROP SCHEMA IF EXISTS competition CASCADE;
DROP SCHEMA IF EXISTS identity CASCADE;
